[program:scheduling-service]
command=/root/app/scheduling-service/venv/bin/gunicorn -w 2 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8002 main:app
directory=/root/app/scheduling-service
user=root
autostart=true
autorestart=true
stderr_logfile=/var/log/scheduling-service.err.log
stdout_logfile=/var/log/scheduling-service.out.log
environment=APP_ENVIRONMENT="production",LOKI_URL="http://localhost:3100",JWT_SECRET_KEY="tu_secreto",DATABASE_URL="mysql+pymysql://dental:1q2w3e4r5t@localhost/dental_scheduling_db",GOOGLE_CLIENT_ID="tu_id",GOOGLE_CLIENT_SECRET="tu_secret",GOOGLE_REDIRECT_URI="https://atuconsul.com/clinic-scheduling-api/v1/oauth/callback",FERNET_KEY="tu_fernet_key",APP_VERSION="1.0.0"
