"""Initial migration

Revision ID: 01496af57eb6
Revises: 
Create Date: 2026-04-11 17:42:03.014625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01496af57eb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('appointment_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.BigInteger(), nullable=False),
    sa.Column('dentist_user_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_user_id', sa.BigInteger(), nullable=False),
    sa.Column('start_time_utc', sa.DateTime(), nullable=False),
    sa.Column('end_time_utc', sa.DateTime(), nullable=False),
    sa.Column('patient_timezone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED', name='appointmentstatus'), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_index(op.f('ix_appointments_clinic_id'), 'appointments', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_appointments_dentist_user_id'), 'appointments', ['dentist_user_id'], unique=False)
    op.create_index(op.f('ix_appointments_google_event_id'), 'appointments', ['google_event_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_user_id'), 'appointments', ['patient_user_id'], unique=False)
    op.create_table('dentist_calendar_configs',
    sa.Column('config_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dentist_user_id', sa.BigInteger(), nullable=False),
    sa.Column('clinic_id', sa.BigInteger(), nullable=False),
    sa.Column('google_email', sa.String(length=255), nullable=True),
    sa.Column('google_access_token', sa.String(length=2048), nullable=True),
    sa.Column('google_refresh_token', sa.String(length=2048), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('sync_enabled', sa.Boolean(), nullable=True),
    sa.Column('default_timezone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_index(op.f('ix_dentist_calendar_configs_clinic_id'), 'dentist_calendar_configs', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_dentist_calendar_configs_dentist_user_id'), 'dentist_calendar_configs', ['dentist_user_id'], unique=False)
    op.create_table('appointment_audit_logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.BigInteger(), nullable=False),
    sa.Column('changed_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.appointment_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment_audit_logs')
    op.drop_index(op.f('ix_dentist_calendar_configs_dentist_user_id'), table_name='dentist_calendar_configs')
    op.drop_index(op.f('ix_dentist_calendar_configs_clinic_id'), table_name='dentist_calendar_configs')
    op.drop_table('dentist_calendar_configs')
    op.drop_index(op.f('ix_appointments_patient_user_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_google_event_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_dentist_user_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_clinic_id'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
